# Generated by Django 5.0.4 on 2024-04-14 06:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('DOB', models.DateField(max_length=10, null=True)),
                ('Pan', models.CharField(max_length=10, null=True)),
                ('Fathers_Name', models.CharField(max_length=200, null=True)),
                ('Profile_img', models.ImageField(default='static\\images\\default_profile.png', upload_to='static\\images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
