# Generated by Django 5.0.4 on 2024-04-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Profile_img',
            field=models.ImageField(blank=True, default='images/default_profile.png', null=True, upload_to='images'),
        ),
    ]
